### ISSUE TITLE
Uncaught TypeError: gl.bindTexSource is not a function     at bindIFrame 

### ISSUE THREAD

**Issue by Digitalisme** [toji/webgl-iframe#2]
Hello, 
My name is Naufal. I'm a student at Brawijaya University.
I'm interested in your project...
I'm tried to run this project, but I had an error on my chrome and safari (I'm using mac btw)

![screen shot 2018-11-22 at 11 50 13 am](https://user-images.githubusercontent.com/34143149/48882595-b9afd180-ee4d-11e8-8305-9464f999f7da.png)

`Uncaught TypeError: gl.bindTexSource is not a function at bindIFrame ((index):343)`

I need your assistance to solve this problem. Thank you.
Sircenly
Naufal

**Comment by kainino0x** [comment]
This project only worked with a locally-patched prototype version of Chromium, but we are no longer working on it. I don't think we will ever add this support in Chromium.

Depending on your use-case, you can directly upload `<video>` to a texture, use 2D canvas for text rendering, or try something else like [this](https://twitter.com/zachernuk/status/958945836842475522).

**Comment by nsmith1024** [comment]
Hi, so can an iFrame be embedded into WebGL so that it can show a webpage using a regular non-modified browser?

**Comment by kainino0x** [comment]
No, this cannot be done in any browser, and this project is no longer being worked on. Check out other possible solutions, like https://zachernuk.neocities.org/webGLizer/.
